# Generated by Django 3.2 on 2021-04-11 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferta_titulo', models.CharField(default=None, max_length=40)),
                ('oferta_texto', models.CharField(default=None, max_length=666)),
                ('oferta_contacto', models.CharField(default=None, max_length=69)),
                ('pub_data', models.DateTimeField(verbose_name='data de publicação')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_titulo', models.CharField(default=None, max_length=40)),
                ('pedido_texto', models.CharField(default=None, max_length=666)),
                ('pedido_contacto', models.CharField(default=None, max_length=69)),
                ('pub_data', models.DateTimeField(verbose_name='data de publicação')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_texto', models.CharField(max_length=666)),
                ('pub_data', models.DateTimeField(verbose_name='data de publicacao')),
                ('like', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto_titulo', models.CharField(default=None, max_length=40)),
                ('projeto_texto', models.CharField(default=None, max_length=666)),
                ('projeto_contacto', models.CharField(default=None, max_length=69)),
                ('projeto_instrumento', models.CharField(default=None, max_length=10)),
                ('pub_data', models.DateTimeField(verbose_name='data de publicação')),
            ],
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venda_titulo', models.CharField(default=None, max_length=40)),
                ('venda_texto', models.CharField(default=None, max_length=666)),
                ('venda_contacto', models.CharField(default=None, max_length=69)),
                ('venda_negociavel', models.BooleanField(default=False)),
                ('venda_preco', models.FloatField(default=None, max_length=8)),
                ('pub_data', models.DateTimeField(verbose_name='data de publicação')),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumento', models.CharField(max_length=10)),
                ('estilo', models.CharField(max_length=10)),
                ('iniciante', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario_texto', models.CharField(max_length=666)),
                ('pub_data', models.DateTimeField(verbose_name='data de publicacao')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.post')),
            ],
        ),
    ]
