# Generated by Django 3.2 on 2021-04-27 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='gosto',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='id',
        ),
        migrations.AddField(
            model_name='comentario',
            name='user',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oferta',
            name='user',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='imagem',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='user',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projeto',
            name='imagem',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='user',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendas',
            name='imagem',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='vendas',
            name='user',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario_texto',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='oferta_contacto',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='oferta_texto',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedido_contacto',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedido_texto',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_texto',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='projeto_contacto',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='projeto_texto',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='venda_contacto',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='venda_texto',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='musica.post')),
                ('user', models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
